baseURL = "https://zhouxinghe-lab.github.io/"
languageCode = "zh-cn"
title = "周星河的数字花园"
theme = "PaperMod"

[params]
    defaultTheme = "auto"
    showReadingTime = true
    showShareButtons = true
    displayFullContent = false
    math = true

[params.homeInfoParams]
    Title = "👋 欢迎来到周星河的数字花园"
    Content = "这里记录着关于医学 AI、大数据技术以及个人成长的思考与沉淀。"