baseURL = "https://zhouxinghe-lab.github.io/"
languageCode = "zh-cn"
title = "周星河的数字花园"
theme = "PaperMod"

[params]
    defaultTheme = "auto"
    showReadingTime = true
    showShareButtons = true
    displayFullContent = false
    math = true
